name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore EveBountyCounter/EveBountyCounter.sln
    
    - name: Build Windows x64
      run: dotnet publish EveBountyCounter/EveBountyCounter/EveBountyCounter.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -o ./publish/win-x64
    
    - name: Build Linux x64
      run: dotnet publish EveBountyCounter/EveBountyCounter/EveBountyCounter.csproj -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -o ./publish/linux-x64
    
    - name: Build macOS x64
      run: dotnet publish EveBountyCounter/EveBountyCounter/EveBountyCounter.csproj -c Release -r osx-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -o ./publish/osx-x64
    
    - name: Create Release Archives
      run: |
        cd publish
        zip -r ../EveBountyCounter-win-x64.zip win-x64/
        tar -czf ../EveBountyCounter-linux-x64.tar.gz -C linux-x64 .
        tar -czf ../EveBountyCounter-osx-x64.tar.gz -C osx-x64 .
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          EveBountyCounter-win-x64.zip
          EveBountyCounter-linux-x64.tar.gz
          EveBountyCounter-osx-x64.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}